[[Players]]
name = "Jack"
elo = 1500
draw = 0

[[Players]]
name = "Jill"
elo = 1400
draw = 1

[[Players]]
name = "James"
elo = 1800
draw = 2

[[Players]]
name = "Jacques"
elo = 2400
draw = 3

[[Players]]
name = "Jacob"
elo = 1300
draw = 4

[[Players]]
name = "Jacqueline"
elo = 1500
draw = 5

[[Players]]
name = "Jesus"
elo = 2200
draw = 6

[[Players]]
name = "Jerome"
elo = 2100
draw = 7

[[Players]]
name = "Jeremy"
elo = 2300
draw = 8

[[Players]]
name = "Jane"
elo = 1900
draw = 9

[[Players]]
name = "Janice"
elo = 1890
draw = 10

[[Players]]
name = "Jasmine"
elo = 1300
draw = 11

[[Players]]
name = "Jasper"
elo = 2000
draw = 12

[[Players]]
name = "Jay"
elo = 2500
draw = 13

[[Players]]
name = "Jordan"
elo = 2350
draw = 14

[[Players]]
name = "John"
elo = 2260
draw = 15
